"""Add contact's status

Revision ID: 418bb87cb5c8
Revises: ca45ebb2c455
Create Date: 2022-06-28 19:16:10.217911

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '418bb87cb5c8'
down_revision = 'ca45ebb2c455'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('contact', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE contact SET status = 'non-subscribed'")
    op.alter_column('contact', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'status')
    # ### end Alembic commands ###
